### ISSUE TITLE
⚡ Modify `IGenerateARandomFloatInTheRangeToAndSaveItAs` method so it accept float interval

### ISSUE THREAD

**Issue by pawelWritesCode** [pawelWritesCode/gdutils#14]
Method `IGenerateARandomFloatInTheRangeToAndSaveItAs` should not only change name, but also be modified so it returns generator func. This func should accept argument that sets rounding for output (for example, to 2 digits after dot) and return generating func that accepts left and right end of interval as float64 instead int like currently.

EDIT: Due to [this](https://github.com/pawelWritesCode/gdutils/issues/14#issuecomment-1078848557) discovery, please do not create generator func. Just create func with signature similar to:

```go
// GenerateFloat64 generates pseudo-random float64 from provided interval and save it in cache under provided cacheKey
func (apiCtx *APIContext) GenerateFloat64(from, to float64, cacheKey string) error
```

**Comment by pawelWritesCode** [comment]
This task connects with #16

**Comment by mikhailbuslaev** [comment]
you want randomize randomizing function?

**Comment by pawelWritesCode** [comment]
Hi, thank you for your contribution, I understand it's not clear what I meant so I'll try to describe it more widely.

First problem I have noticed with function `IGenerateARandomFloatInTheRangeToAndSaveItAs` is that it rounds generated random float to two digits after dot. 

[this](https://github.com/pawelWritesCode/gdutils/blob/master/steps.go#L443) is line of code responsible for that.

I noticed some users may not want round it to 2nd digit, but to other precision. That's why I came up with idea of writting closure, that returns random float generator with predefined rounding.

Second thing is that it accepts interval of "int", not float - it is subject to change as you correctly noticed.

Third thing is name of method itself. Now it has "godog" style, where method name reflects step it is used for. I think every method in library should change its name to much shorter, more general one.


Gathering what I wrote above I would sugest new signature to be something like this:
```go
// GenerateFloat64 creates pseudo random float64 generator with predefined rounding precision
func (apiCtx *APIContext) CreateFloat64Generator(round int) func(from, to float64, cacheKey string) error
```

Soon I'll check your PR, please let me know if everything I wrote above is clear

**Comment by pawelWritesCode** [comment]
As I dig deeper into issue, I found out this: 

https://stackoverflow.com/questions/41159492/format-float-in-golang-html-template

This states, that current template engine implementation (standard [text/template](https://pkg.go.dev/text/template)) has ability to pass functions to template engine. That mean there is ability to round floating values. 

I created successful unit test to prove it, you can see it in this [commit](https://github.com/pawelWritesCode/gdutils/commit/61cce00f5e97a806e2454c5e68a707291d92376e), already merged to `v15` branch.

Sorry for the mess, but in context of above discovery I'd like to ask you to simply write function with similar signature to this:

```go
// GenerateFloat64 generates pseudo-random float64 from provided interval and save it in cache under provided cacheKey
func (apiCtx *APIContext) GenerateFloat64(from, to float64, cacheKey string) error
```

Luckily, you are very close to obtain it.

PS: Your step (`GenerateFloat64` func) should not contain rounding inside like [this](https://github.com/pawelWritesCode/gdutils/blob/master/steps.go#L443)
