### ISSUE TITLE
go-swagger

### ISSUE THREAD

**Issue by kieranbop1990** [pawelWritesCode/gdutils#23]
I just stumbled across this repo and it is brilliant. Have you ever explored using the client generated code from https://github.com/go-swagger/go-swagger to wrap around godog tests so that we can leverage all the request objects? Or is that something we could collaborate on here?

**Comment by pawelWritesCode** [comment]
Hi, 

I have never used `go-swagger` yet, therefore I have never explored this topic. However, this seems interesting to me and I would like to learn a little bit about `go-swagger`.

I propose following: during this week (_09.05 - 13.05_) I'll try to understand basic concepts behind this project. I saw it has rich documentation - so hopefully it won't be a problem. Then on weekend (14.05 - 15.05), we can set a meeting via google or another suitable for you tool and we can talk about your proposition and decide whether is it something possible to do and are we going to do it. Are you up to ?

**Comment by kieranbop1990** [comment]
Sure. Can you do 13.05 by any chance? 
The go-swagger client is the interesting part for tests as it builds a http client and implements all the methods to call your service under test. I'm exploring options of how I can wrap them around with something like godog to leverage all this functionality that is auto generated for us.

**Comment by pawelWritesCode** [comment]
Oki, I propose 7pm Warsaw time tomorrow are you up to ? 

If you prefer another date, please mail me: salata02 (at) gmail.com 
I propose to move conversation from issue to email so it will be faster.
