### ISSUE TITLE
⚡ Create examples for methods

### ISSUE THREAD

**Issue by pawelWritesCode** [pawelWritesCode/gdutils#28]
Task objective is to check all possible methods and try to create at least one [example](https://go.dev/blog/examples) for each.

**Comment by 87prashant** [comment]
Hi,
I am a newcomer looking forward to contributing and searching for good first issues. 
I guess there is a typo in the above statement "Task objective is **too**..." -> "Task objective is **to**..."

**Comment by pawelWritesCode** [comment]
@87prashant hi, you are right, thanks for spoting typo! Do you have any experience with testable examples in go ?

**Comment by 87prashant** [comment]
Not currently, just exploring the open source world and learning
